### ISSUE TITLE
Use TAMSAT rainfall directly

### ISSUE THREAD

**Issue by jgomezdans** [NCEO-ODA/ghana_data#15]
@Ewan82 suggests using the TAMSAT rainfall data directly. His code to translate that into GeoTIFF is [here](https://github.com/Ewan82/tamsat_anom_plots/blob/master/tamsatrfe_to_tif.py)

@Ewan82 I don't think I have access to that folder, so can have a look at some files that you create and see whether they look OK ;)

**Comment by Ewan82** [comment]
@jgomezdans nice! I will finish processing it and then let you know where it is to see if it looks correct! Thanks!

**Comment by jgomezdans** [comment]
Or maybe just do a single year first?

**Comment by Ewan82** [comment]
Yep sure 2000 is here: /gws/nopw/j04/odanceo/public/soil_moisture/nc/GTiff/tamsat_rfe_filled_2000.tif

**Comment by jgomezdans** [comment]
OK, it looks as if it's OK (matches the coastlines ;-D)

**Comment by Ewan82** [comment]
Lovely stuff! Have processed the rest of the years now too!
